name: SSVEP Interface Check

on: 
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: "3.8.5"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f SSVEP-Interface/requirements.txt ]; then pip install -r SSVEP-Interface/requirements.txt; fi
